source 'https://rubygems.org'

group :development do
  gem 'guard'
  gem 'rb-readline'
  gem 'foodcritic', '~> 6.2'
  gem 'guard-foodcritic'
  gem 'guard-rubocop'
  gem 'terminal-notifier-guard'
  gem 'guard-rspec'
  gem 'rspec_junit_formatter'
end

group :rake do
  gem 'rake'
  gem 'tomlrb'
end

group :lint do
  gem 'rubocop', '~> 0.38'
end

group :unit do
  gem 'berkshelf', '~> 4.3'
  gem 'chefspec', '~> 4.6'
end

group :kitchen_common do
  gem 'test-kitchen', '~> 1.7'
end

group :kitchen_vagrant do
  gem 'kitchen-vagrant', '~> 0.20'
end
