# YTS Cookbook Rakefile
# 06/03/2016
# Created by Ryan Moon

##
# Requires
##

require 'rspec/core/rake_task'
require 'rubocop/rake_task'
require 'foodcritic'
require 'kitchen'

##
# Style tests, Rubocop and Foodcritic
##

namespace :style do
  desc 'Run Ruby style checks'
  RuboCop::RakeTask.new(:ruby)

  desc 'Run Chef style checks'
  FoodCritic::Rake::LintTask.new(:chef) do |t|
    t.options = {
      fail_tags: ['any']
    }
  end
end

desc 'Run all style checks'
task style: ['style:chef', 'style:ruby']

##
# Rspec and ChefSpec
##

desc 'Run ChefSpec examples'
RSpec::Core::RakeTask.new(:spec)

##
# Integration tests with test-kitchen
##

namespace :integration do
  desc 'Run Test Kitchen with Vagrant'
  task :vagrant do
    Kitchen.logger = Kitchen.default_file_logger
    Kitchen::Config.new.instances.each do |instance|
      instance.test(:always)
    end
  end
end

##
# Berkshelf, did not provide desc so that you
# can only call them with the grouped
# rake call upload or wrong
##

namespace :berks do
  task :install do
    sh 'chef exec berks install'
  end
  task :upload do
    sh 'chef exec berks upload'
  end
  task :force do
    sh 'chef exec berks upload --force'
  end
end

desc 'Workflow to add cookbook to server'
task upload: ['berks:install', 'berks:upload']

desc 'Workflow to forcefully add cookbook to server'
task wrong: ['berks:install', 'berks:force']

##
# Default
##

task default: %w(style spec)
